name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Download data
        run: python3 src/get_data.py --output_folder data/raw

      - name: Train model
        run: python3 src/train.py --config params.yaml

  build-and-push-docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # We need to restore the data and model from DVC
      # For now, we are re-downloading and re-training, which is not ideal.
      # In a real-world scenario, you would use `dvc pull` here after setting up remote storage.
      - name: Set up DVC
        uses: iterative/setup-dvc@v1

      # Re-creating data and model as we don't have DVC remote storage yet
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install all dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Download data
        run: python3 src/get_data.py --output_folder data/raw
        
      - name: Train model to generate artifact
        run: python3 src/train.py --config params.yaml

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Build and push the Docker image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-for-ml-model:latest 